/**
 * CircuitPreview — renders a circuit thumbnail using the real wokwi-element SVGs.
 *
 * Uses a HTML <div> + absolutely-positioned <img> elements (not SVG <image>),
 * because HTML <img> loads complex SVGs (xlink:href, filters, mm units) reliably
 * while SVG <image href> often fails for anything beyond simple shapes.
 *
 * Wires are drawn on an SVG overlay on top of the component images.
 *
 * SVGs are generated by scripts/generate-component-svgs.cjs at build time
 * and served from /component-svgs/ as static assets.
 *
 * Board handling:
 *  - arduino-uno examples: board IS in components[] as 'wokwi-arduino-uno'
 *  - pico / esp32 examples: board is NOT in components[] — it comes from boardType
 *    and is injected at a default position by this component
 */

import React from 'react';
import type { ExampleProject, ExampleBoard } from '../../data/examples';

// ── Natural display sizes (px on the simulator canvas) ──────────────────────
interface CompDef {
  svg: string;   // filename under /component-svgs/
  w: number;     // natural width in canvas-space pixels
  h: number;     // natural height in canvas-space pixels
}

const COMP_DEFS: Record<string, CompDef> = {
  // Boards
  'wokwi-arduino-uno':             { svg: 'arduino-uno.svg',             w: 274, h: 202 },
  'wokwi-arduino-nano':            { svg: 'arduino-nano.svg',            w: 170, h:  67 },
  'wokwi-arduino-mega':            { svg: 'arduino-mega.svg',            w: 388, h: 192 },
  'wokwi-esp32-devkit-v1':         { svg: 'esp32-devkit-v1.svg',         w: 107, h: 204 },
  // Passive / output
  'wokwi-led':                     { svg: 'led.svg',                     w:  40, h:  50 },
  'wokwi-rgb-led':                 { svg: 'rgb-led.svg',                 w:  42, h:  73 },
  'wokwi-resistor':                { svg: 'resistor.svg',                w:  59, h:  11 },
  'wokwi-neopixel':                { svg: 'neopixel.svg',                w:  21, h:  19 },
  'wokwi-neopixel-matrix':         { svg: 'neopixel-matrix.svg',         w:  97, h:  87 },
  'wokwi-led-ring':                { svg: 'led-ring.svg',                w: 118, h: 129 },
  'wokwi-buzzer':                  { svg: 'buzzer.svg',                  w:  30, h:  30 },
  // Input
  'wokwi-pushbutton':              { svg: 'pushbutton.svg',              w:  67, h:  45 },
  'wokwi-pushbutton-6mm':          { svg: 'pushbutton-6mm.svg',          w:  28, h:  23 },
  'wokwi-potentiometer':           { svg: 'potentiometer.svg',           w:  76, h:  76 },
  'wokwi-analog-joystick':         { svg: 'analog-joystick.svg',         w: 103, h: 120 },
  // Sensors
  'wokwi-dht22':                   { svg: 'dht22.svg',                   w:  57, h: 117 },
  'wokwi-hc-sr04':                 { svg: 'hc-sr04.svg',                 w: 170, h:  94 },
  'wokwi-mpu6050':                 { svg: 'mpu6050.svg',                 w:  82, h:  61 },
  'wokwi-ntc-temperature-sensor':  { svg: 'ntc-temperature-sensor.svg',  w: 136, h:  72 },
  'wokwi-photoresistor-sensor':    { svg: 'photoresistor-sensor.svg',    w: 174, h:  62 },
  'wokwi-pir-motion-sensor':       { svg: 'pir-motion-sensor.svg',       w:  91, h:  92 },
  'wokwi-ds1307':                  { svg: 'ds1307.svg',                  w:  98, h:  84 },
  'wokwi-bmp280':                  { svg: 'mpu6050.svg',                 w:  82, h:  61 },
  // Displays
  'wokwi-7segment':                { svg: '7segment.svg',                w:  47, h:  83 },
  'wokwi-ili9341':                 { svg: 'ili9341.svg',                 w: 176, h: 293 },
  'wokwi-lcd2004':                 { svg: 'lcd2004.svg',                 w: 356, h: 180 },
  // Motors
  'wokwi-servo':                   { svg: 'servo.svg',                   w: 170, h: 120 },
};

// Board SVG definitions — used when the board is implicit (pico / esp32 pattern)
const BOARD_DEFS: Record<string, CompDef> = {
  'arduino-uno':       { svg: 'arduino-uno.svg',       w: 274, h: 202 },
  'arduino-nano':      { svg: 'arduino-nano.svg',      w: 170, h:  67 },
  'arduino-mega':      { svg: 'arduino-mega.svg',      w: 388, h: 192 },
  'raspberry-pi-pico': { svg: 'raspberry-pi-pico.svg', w:  79, h: 200 },
  'raspberry-pi-3':    { svg: 'raspberry-pi-3.svg',    w: 200, h: 135 },
  'esp32':             { svg: 'esp32-devkit-v1.svg',   w: 107, h: 204 },
  'esp32-s3':          { svg: 'esp32-devkit-v1.svg',   w: 107, h: 204 },
  'esp32-c3':          { svg: 'esp32-devkit-v1.svg',   w: 107, h: 204 },
};

// LED color → SVG filename
const LED_COLOR_SVG: Record<string, string> = {
  red:    'led.svg',
  green:  'led-green.svg',
  blue:   'led-blue.svg',
  yellow: 'led-yellow.svg',
};

function getCompDef(type: string, props: Record<string, any>): CompDef {
  if (type === 'wokwi-led') {
    const colorSvg = LED_COLOR_SVG[(props.color as string)?.toLowerCase()] ?? 'wokwi-led.svg';
    return { ...COMP_DEFS['wokwi-led'], svg: colorSvg };
  }
  return COMP_DEFS[type] ?? { svg: '', w: 50, h: 50 };
}

// Whether a component type is the main board (already registered via boardType)
function isBoardType(type: string): boolean {
  return type.includes('arduino-uno') ||
         type.includes('arduino-nano') ||
         type.includes('arduino-mega') ||
         type.includes('esp32-devkit') ||
         type.includes('raspberry-pi-pico') ||
         type.includes('nano-rp2040');
}

// ── Main component ───────────────────────────────────────────────────────────

interface CircuitPreviewProps {
  example: ExampleProject;
  width?: number;
  height?: number;
  background?: string;
  className?: string;
  style?: React.CSSProperties;
}

interface LayoutItem {
  id: string;
  x: number;
  y: number;
  def: CompDef;
}

export const CircuitPreview: React.FC<CircuitPreviewProps> = ({
  example,
  width  = 300,
  height = 180,
  background = '#1a1a1a',
  className,
  style,
}) => {
  const items: LayoutItem[] = [];

  // ── Build layout items ───────────────────────────────────────────────────
  if (example.boards && example.boards.length > 0) {
    // Multi-board layout
    example.boards.forEach((b: ExampleBoard) => {
      const def = BOARD_DEFS[b.boardKind] ?? { svg: '', w: 200, h: 140 };
      items.push({ id: b.boardKind, x: b.x, y: b.y, def });
    });
  } else {
    const boardKind = example.boardType ?? 'arduino-uno';
    const boardDef  = BOARD_DEFS[boardKind];

    // Check if the board is explicitly listed in components[]
    const boardInComponents = example.components.some(c => isBoardType(c.type));

    if (boardDef && !boardInComponents) {
      // Board is implicit (pico, esp32, nano examples) — inject at default position
      // Position it to the left of the other components
      const minCompX = example.components.length > 0
        ? Math.min(...example.components.map(c => c.x))
        : 400;
      const avgCompY = example.components.length > 0
        ? example.components.reduce((s, c) => s + c.y, 0) / example.components.length
        : 150;
      const boardX = Math.max(40, minCompX - boardDef.w - 60);
      const boardY = Math.max(40, avgCompY - boardDef.h / 2);
      items.push({ id: boardKind + '-board', x: boardX, y: boardY, def: boardDef });
    }

    // Add all components from the example
    example.components.forEach((c) => {
      // For board components that ARE in components[], use the board SVG def
      const def = isBoardType(c.type) && boardDef
        ? boardDef
        : getCompDef(c.type, c.properties ?? {});
      items.push({ id: c.id, x: c.x, y: c.y, def });
    });
  }

  // ── Bounding box & scale ─────────────────────────────────────────────────
  const PAD = 12;

  if (items.length === 0) {
    return (
      <div style={{ width, height, background, display: 'flex', alignItems: 'center', justifyContent: 'center', ...style }} className={className}>
        <span style={{ color: '#555', fontSize: 12 }}>No components</span>
      </div>
    );
  }

  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  items.forEach(({ x, y, def }) => {
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x + def.w);
    maxY = Math.max(maxY, y + def.h);
  });

  const boxW = maxX - minX + PAD * 2;
  const boxH = maxY - minY + PAD * 2;
  const scale = Math.min(width / boxW, height / boxH, 1.5); // cap at 1.5× to avoid huge boards
  const dx    = (width  - boxW * scale) / 2 - (minX - PAD) * scale;
  const dy    = (height - boxH * scale) / 2 - (minY - PAD) * scale;

  // Centre of each item in rendered space (for wire routing)
  const centreMap: Record<string, [number, number]> = {};
  const boardKindForCentre = (!example.boards && example.boardType) ? example.boardType : null;
  items.forEach(({ id, x, y, def }) => {
    const centre: [number, number] = [
      (x + def.w / 2) * scale + dx,
      (y + def.h / 2) * scale + dy,
    ];
    centreMap[id] = centre;
    // Also register implicit boards under their plain boardKind so that wires
    // using componentId: 'esp32' / 'raspberry-pi-pico' etc. resolve correctly.
    if (boardKindForCentre && id === boardKindForCentre + '-board') {
      centreMap[boardKindForCentre] = centre;
    }
  });

  return (
    <div
      className={className}
      style={{
        position: 'relative',
        width,
        height,
        background,
        overflow: 'hidden',
        borderRadius: 'inherit',
        ...style,
      }}
    >
      {/* ── Component images ─────────────────────────────────────────────── */}
      {items.map(({ id, x, y, def }) => {
        if (!def.svg) return null;
        const px = x * scale + dx;
        const py = y * scale + dy;
        const pw = def.w * scale;
        const ph = def.h * scale;
        return (
          <img
            key={id}
            src={`/component-svgs/${def.svg}`}
            alt=""
            style={{
              position: 'absolute',
              left:   px,
              top:    py,
              width:  pw,
              height: ph,
              imageRendering: 'auto',
              // Filter to slightly darken components so they read well on dark bg
              filter: 'drop-shadow(0 1px 2px rgba(0,0,0,0.5))',
            }}
          />
        );
      })}

    </div>
  );
};
